version: "3.8"
services:
  app:
    build:
      context: .
    environment:
      - DD_SITE
      - DD_HOSTNAME
      - GEO_USERNAME
      - GEO_PASSWORD
      - DD_API_KEY
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
